"""change passowrd column

Revision ID: 130c7d6f7afd
Revises: 9cbbad2139ec
Create Date: 2024-01-27 10:51:18.156461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130c7d6f7afd'
down_revision = '9cbbad2139ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               type_=sa.LargeBinary(length=60),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.LargeBinary(length=60),
               type_=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
